### ISSUE TITLE
Typo in Section 15.10 on Type Classes

### ISSUE THREAD

**Issue by edufuga** [fcpbook/resources#2]
# Typo in Section 15.10 on Type Classes

Skimming through the book, I saw a tiny typo in page 246 (towards the middle of the page):

> You can then use an object of type `Title[A]` to display the title of a value of type `A`

That should be `Titled[A]`. The type class is called Title**d** (i.e. the "d" is missing).

**Comment by charpov** [comment]
Thanks. You're good at finding those! Added to the errata list (https://www.fcpbook.org/errata.html).
